name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute Deployment Commands
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server_ip << 'EOF'
            cd /root/kata-watch-list/orchestration
            git pull origin main
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d --force-recreate
          EOF
